baseURL = "https://examplesite.com"
disqusShortname = "themefisher-template"
googleAnalytics = ""
paginate = "6"
theme = "lose2gain"
title = "Lose To Gain | Your Personal Trainer"
[markup.goldmark.renderer]
unsafe = true
[[menu.about]]
name = "Portfolio"
url = "portfolio"
weight = 2
[[menu.about]]
name = "About"
url = "about"
weight = 1
[[menu.information]]
name = "Portfolio"
url = "portfolio"
weight = 2
[[menu.information]]
name = "About"
url = "about"
weight = 1
[[menu.main]]
name = "Product"
parent = "Pages"
url = "product"
weight = 4
[[menu.main]]
name = "FAQ"
parent = "Pages"
url = "faq"
weight = 3
[[menu.main]]
name = "Terms & Conditions"
parent = "Pages"
url = "terms-conditions"
weight = 2
[[menu.main]]
hasChildren = true
name = "Pages"
weight = 6
[[menu.main]]
name = "Contact"
url = "contact"
weight = 5
[[menu.main]]
name = "Client Reviews"
url = "story"
weight = 4
[[menu.main]]
name = "Coaching"
url = "mentor"
weight = 3
[[menu.main]]
name = "Blog"
parent = "Pages"
url = "blog"
weight = 1
[[menu.main]]
name = "About"
url = "about"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS"]
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
custom_script = ""
description = "This is meta description"
favicon = "images/favicon.png"
footer_content = "Lorem ipsum dolor sit sed dmi amet, consectetur adipiscing. Cdo tellus sed condimentum volutpat."
logo = "images/logo.png"
logo_width = "135px"
[params.cookies]
enable = false
expire_days = 2
[params.navigation_button]
enable = false
label = "get a quote"
link = "contact"
[[params.plugins.css]]
attributes = "media='screen'"
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
attributes = "media='screen'"
link = "plugins/slick/slick.css"
[[params.plugins.css]]
attributes = "media='screen'"
link = "plugins/slick/slick-theme.css"
[[params.plugins.css]]
attributes = ""
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/twentytwenty/css/twentytwenty.css"
[[params.plugins.css]]
attributes = "media='screen'"
link = "plugins/swiper/swiper.css"
[[params.plugins.js]]
attributes = ""
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/twentytwenty/js/jquery.event.move.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/twentytwenty/js/jquery.twentytwenty.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/rating/rating.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/swiper/swiper.min.js"
[[params.plugins.js]]
attributes = ""
link = "https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"
[params.preloader]
enable = false
preloader = ""
[[params.social]]
icon = "fab fa-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "fab fa-twitter"
link = "#"
title = "twitter"
[[params.social]]
icon = "fab fa-instagram"
link = "#"
title = "instagram"
