---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Homepage
- type: document
  path: data/home.yml
  label: homepage
- type: heading
  label: Blog
- type: document
  path: content/blog/_index.md
  label: Blog Page
- type: directory
  path: content/blog
  label: Blog Post
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: heading
  label: Mentor
- type: document
  path: content/mentor/_index.md
  label: Mentor Page
- type: directory
  path: content/mentor
  label: Mentor
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - mentor
- type: heading
  label: Program
- type: document
  path: content/program/_index.md
  label: Program Page
  match: "**/*"
- type: directory
  path: content/program
  label: Program
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - program
- type: heading
  label: Story
- type: document
  path: content/story/_index.md
  label: Story Page
- type: directory
  path: content/story
  label: Story
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - story
- type: heading
  label: Product
- type: document
  path: content/product/_index.md
  label: Product Page
- type: directory
  path: content/product
  label: Product
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - product
- type: heading
  label: Others Page
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: heading
  label: Configuration
- type: document
  path: config.toml
  label: Configuration
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.79.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.79.0
