---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: price
  label: price
- type: text
  name: badge
  label: badge
- type: datetime
  name: date
  label: date
- type: image_gallery
  name: images
  label: images
- type: text
  name: category
  label: category
- type: textarea
  name: description
  label: description
- type: field_group_list
  name: information
  label: information
  fields:
  - type: text
    name: name
    label: name
  - type: text
    name: info
    label: info
